package com.hibernate.model;

// Generated 2015-3-20 21:36:04 by Hibernate Tools 3.2.2.GA

/**
 * Bbs generated by hbm2java
 */
public class Bbs implements java.io.Serializable {

	private Integer id;
	private String title;
	private String time;
	private String source;
	private String content;
	private String http;
	private Integer commentSum;

	public Bbs() {
	}

	public Bbs(String title, String time, String source, String content,
			String http, Integer commentSum) {
		this.title = title;
		this.time = time;
		this.source = source;
		this.content = content;
		this.http = http;
		this.commentSum = commentSum;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public String getTitle() {
		return this.title;
	}

	public void setTitle(String title) {
		this.title = title;
	}

	public String getTime() {
		return this.time;
	}

	public void setTime(String time) {
		this.time = time;
	}

	public String getSource() {
		return this.source;
	}

	public void setSource(String source) {
		this.source = source;
	}

	public String getContent() {
		return this.content;
	}

	public void setContent(String content) {
		this.content = content;
	}

	public String getHttp() {
		return this.http;
	}

	public void setHttp(String http) {
		this.http = http;
	}

	public Integer getCommentSum() {
		return this.commentSum;
	}

	public void setCommentSum(Integer commentSum) {
		this.commentSum = commentSum;
	}

}
