package com.hibernate.model;

// Generated 2015-3-22 13:12:17 by Hibernate Tools 3.2.2.GA

/**
 * Ipagent generated by hbm2java
 */
public class Ipagent implements java.io.Serializable {

	private Integer id;
	private String ip;
	private Integer port;
	private String can;

	public Ipagent() {
	}

	public Ipagent(String ip, Integer port, String can) {
		this.ip = ip;
		this.port = port;
		this.can = can;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public String getIp() {
		return this.ip;
	}

	public void setIp(String ip) {
		this.ip = ip;
	}

	public Integer getPort() {
		return this.port;
	}

	public void setPort(Integer port) {
		this.port = port;
	}

	public String getCan() {
		return this.can;
	}

	public void setCan(String can) {
		this.can = can;
	}

}
