package com.hibernate.model;

// Generated 2015-3-22 13:12:17 by Hibernate Tools 3.2.2.GA

/**
 * Search generated by hbm2java
 */
public class Search implements java.io.Serializable {

	private Integer id;
	private String title;
	private String content;
	private String time;
	private String http;
	private String source;

	public Search() {
	}

	public Search(String title, String content, String time, String http,
			String source) {
		this.title = title;
		this.content = content;
		this.time = time;
		this.http = http;
		this.source = source;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public String getTitle() {
		return this.title;
	}

	public void setTitle(String title) {
		this.title = title;
	}

	public String getContent() {
		return this.content;
	}

	public void setContent(String content) {
		this.content = content;
	}

	public String getTime() {
		return this.time;
	}

	public void setTime(String time) {
		this.time = time;
	}

	public String getHttp() {
		return this.http;
	}

	public void setHttp(String http) {
		this.http = http;
	}

	public String getSource() {
		return this.source;
	}

	public void setSource(String source) {
		this.source = source;
	}

}
