package com.hibernate.model;

// Generated 2015-3-20 21:36:04 by Hibernate Tools 3.2.2.GA

import java.util.Date;

/**
 * WeiboSearch generated by hbm2java
 */
public class WeiboSearch implements java.io.Serializable {

	private Integer id;
	private String userid;
	private Date time;
	private String content;
	private String source;
	private String keyWord;

	public WeiboSearch() {
	}

	public WeiboSearch(String userid, Date time, String content, String source,
			String keyWord) {
		this.userid = userid;
		this.time = time;
		this.content = content;
		this.source = source;
		this.keyWord = keyWord;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public String getUserid() {
		return this.userid;
	}

	public void setUserid(String userid) {
		this.userid = userid;
	}

	public Date getTime() {
		return this.time;
	}

	public void setTime(Date time) {
		this.time = time;
	}

	public String getContent() {
		return this.content;
	}

	public void setContent(String content) {
		this.content = content;
	}

	public String getSource() {
		return this.source;
	}

	public void setSource(String source) {
		this.source = source;
	}

	public String getKeyWord() {
		return this.keyWord;
	}

	public void setKeyWord(String keyWord) {
		this.keyWord = keyWord;
	}

}
