package com.hibernate.model;

// Generated 2015-3-22 13:12:17 by Hibernate Tools 3.2.2.GA

import java.util.Date;

/**
 * Weixin generated by hbm2java
 */
public class Weixin implements java.io.Serializable {

	private Integer id;
	private String title;
	private Date time;
	private String source;
	private String content;
	private String http;

	public Weixin() {
	}

	public Weixin(String title, Date time, String source, String content,
			String http) {
		this.title = title;
		this.time = time;
		this.source = source;
		this.content = content;
		this.http = http;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public String getTitle() {
		return this.title;
	}

	public void setTitle(String title) {
		this.title = title;
	}

	public Date getTime() {
		return this.time;
	}

	public void setTime(Date time) {
		this.time = time;
	}

	public String getSource() {
		return this.source;
	}

	public void setSource(String source) {
		this.source = source;
	}

	public String getContent() {
		return this.content;
	}

	public void setContent(String content) {
		this.content = content;
	}

	public String getHttp() {
		return this.http;
	}

	public void setHttp(String http) {
		this.http = http;
	}

}
